# Generated by Django 5.1.6 on 2025-04-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='quantity',
            field=models.CharField(blank=True, help_text="Например, '200 г', '1 шт.'", max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='allergens',
            field=models.CharField(blank=True, help_text='Укажите возможные аллергены', max_length=255),
        ),
    ]
